config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  root 'static_pages#landing'
  get 'static_pages/home'
  get 'static_pages/faq'
  get 'static_pages/healing'
  
  resources :portfolios do
    resources :flashs
  end

  resources :contacts, only: [:new, :create]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,   :validate => true
    attribute :nickname,  :captcha  => true
  
    def headers
      {
        :subject => "Contact Form",
        :to => "paul.poitrenaud@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end
  

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many_attached :flashs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new 
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
  redirect_to root_path, notice: 'Message envoyé'
    else
      flash.now[:error] = 'Erreur, veuillez réessayer.'
      render :new
    end
  end
end

app/controllers/flashs_controller.rb
class FlashsController < ApplicationController
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
        @portfolios = Portfolio.all
    end
    def show
        @portfolio = Portfolio.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def landing
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/flashs_helper.rb
module FlashsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/new.html.erb
<%= form_for @contact do |f| %>
    <% if flash[:error].present? %>
        <p> flash[:error]</p>
    <% end %>
    <%= f.label :name %> <br>
    <%= f.text_field :name, required: true %>

    <br>
    <%= f.label :email %> <br>
    <%= f.text_field :email, required: true %>

    <br>
    <%= f.label :message %> <br>
    <%= f.text_area :message, as: :text %>

 
    <%= f.label :nickname %> <br>
    <%= f.text_field :nickname, hint: 'leave this field blank' %>


    <%= f.submit 'Send Message', class: "button" %>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="grey vanilla-bean-text tahoma-text">
		<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-3 no-padding">
				<div class="padding">
					<h5 class="lucida-text">A propos</h5>
					<p>Cowboi.jpeg est tatoueur depuis 2015. Avec plus de 8500 tatouages à son actif, vous pouvez y aller les yeux fermés.</p>
				</div>
			</div>
			<div class="col-sm-12 col-md-3 no-padding">
				<div class="padding">
					<h5 class="lucida-text">Liens</h5>
					<ul class="comic-sans-text">
						<li><a href="https://www.instagram.com/cowboi.jpeg/">Instagram</a></li>
						<li><a href="#">top_secret_1997.dvix.rip</a></li>
					</ul>
				</div>
			</div>
		</div>
		</div>
	</footer>

app/views/layouts/_navbar.html.erb
<div class="brick b100 no-padding black draggable">
				<div class="glued">
					<div class="row">
						<div class="col-xs-12 col-sm-6 no-padding">
							<nav class="simple bold">
								<ul class="courier-new-text flow-text lime-text">
									<li class="red invert-hover"><a href="/static_pages/home" class="black-text blue-text-shadow">Retour à l'accueil</a></li>
									<li class="red invert-hover"><a href="/contacts/new" class="black-text blue-text-shadow blink-fast">Prendre rendez-vous</a></li>
									<li class="red invert-hover"><a href="/portfolios" class="black-text blue-text-shadow">Portfolio</a></li>
								</ul>
							</nav>
						</div>
						<div class="col-xs-12 col-sm-6 no-padding">
							<nav class="simple blue">
								<ul class="comic-sans-text flow-text lime-text">
									<li class="invert-hover"><a href="/static_pages/healing" class="lime-text">Feuille de soin</a></li>
									<li class="invert-hover"><a href="/static_pages/faq" class="lime-text">FAQ</a></li>
									<li class="invert-hover"><a href="/static_pages/faq" class="lime-text">Shoppe</a></li>
								</ul>
							</nav>
						</div>
					</div>
                    <div class="scroll-left">
                    <div class="scroll-item lime invert-hover bold black-text lucida-text">
					<p class="baffle-longer">Les dates du cowboi_wOrld_tOur.torrent : 12 Janvier à Besançon, 34 Avril à Austin, Texas, 09 Septembre Dans ton Cul </p>
                    </div>
                    </div>
				</div>
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cowboi.jpeg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
	<title>Brutalist Framework || Splash Page Template 001</title>
	<meta name="description" content="A simple framework for the brutalist web design trend." />
	<meta name="keywords" content="brutalism, brutalist, framework, css, open source, style, design trend" />
	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary">
	<meta name="twitter:site" content="@pinebuilder">
	<meta name="twitter:title" content="Brutalist Framework || Splash Page Template 001">
	<meta name="twitter:description" content="A simple framework for the brutalist web design trend.">
	<meta name="twitter:creator" content="@pinebuilder">
	<!-- Twitter Summary card images must be at least 120x120px -->
	<meta name="twitter:image" content="http://www.brutalistframework.com/assets/images/brutalist-framework512.jpg">

	<!-- Open Graph data -->
	<meta property="og:title" content="Brutalist Framework || Splash Page Template 001" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="http://www.brutalistframework.com" />
	<meta property="og:image" content="http://www.brutalistframework.com/assets/images/brutalist-framework512.jpg" />
	<meta property="og:description" content="A simple framework for the brutalist web design trend." /> 
	<meta property="og:site_name" content="Brutalist Framework" />

	<!-- Icons -->
	<link rel="shortcut icon" href="assets/icons/bf44.png" type="image/x-icon" />
	<link rel="icon" href="assets/icons/bf15.ico" type="image/x-icon" />
	<link rel="apple-touch-icon" href="assets/icons/bf57.png" />
	<!-- CSS  -->
	<link href="../css/core/core.css" type="text/css" rel="stylesheet" media="screen,projection"/>
	<link href="css/theme.css" type="text/css" rel="stylesheet" media="screen,projection" />
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<% unless action_name == "landing" %>
	<%= render "layouts/navbar" %>
	<% end %>

    <%= yield %>

	<% unless action_name == "landing" %>
	<%= render "layouts/footer" %>
	<% end %>
    
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-93046252-1', 'auto');
  ga('send', 'pageview');
</script>
  </body>
</html>

app/views/portfolios/index.html.erb
 <p> P O R T F O L I O </p>

app/views/static_pages/faq.html.erb
	<div class="blog-post-cover vanilla-bean" style="margin-top: 4em; padding-top: 3.5em;">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-8">
					<div class="box-shadow-quad bubble-gum comfortable draggable glitch">
						<h2 class="courier-new-text fittext-h3 heavy brutal-text-neon">Foire Aux Questions</h2>
						<h3 class="deep-orange-text comic-sans-text flow-text">Vous avez des questions ? En voici les réponses. (si votre question ne figure pas ici n'hésitez pas à m'écrire)</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div style="display: block; clear: both;"></div>

	<div class="vanilla-bean">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-9 col-lg-9">
					<div class="double-col pad50">
                        <blockquote class="flow-text comic-sans-text blue-text">Ça pique les tatouages ? J'ai peur des aiguilles.</blockquote> 
                        <p class="comic-sans-text smaller oblique"> Jean-Charles, 12 ans et demi </p><br/>
						<p class="tahoma-text charcoal-text">
                        Oui ça pique gros blaireau, mais personne en est mort tkt.
						</p><br/>
						<hr class="jagged-rule-dark" />
                        <blockquote class="flow-text comic-sans-text blue-text">Sa coutte cher de ce faire tatooez ?</blockquote> 
                        <p class="comic-sans-text smaller oblique"> Cindy, 18 ans </p><br/><br/>
						<p class="tahoma-text charcoal-text">
                        Tout dépend de ton projet. Check mes stories sur insta, je met souvent les prix directement dessus. Ils ne sont pas négociables, même si ton cousin Kévin les fait pour moins cher.
						</p><br/>
						<hr class="jagged-rule-dark" />
                        <blockquote class="flow-text comic-sans-text blue-text">Faites vous les projets personnels ? Je trouve vos flashs vulgaires.</blockquote> 
                        <p class="comic-sans-text smaller oblique"> Edouardine, 33 ans 1/3 </p><br/>
						<p class="tahoma-text charcoal-text">
                        Je n'accepte les projets persos que très rarement, envoie moi un email et on pourra en discuter !
						</p><br/>
						<hr class="jagged-rule-dark" />
                        <blockquote class="flow-text comic-sans-text blue-text">J'ai rdv à la piscine mais tu viens de me tatouer, ça craint ?</blockquote> 
                        <p class="comic-sans-text smaller oblique"> Tonino, région PACA </p><br/>
						<p class="tahoma-text charcoal-text">
                        Yes ça craint un max même, pour plus d'info, je t'invite à consulter ma fiche de soin.
						</p><br/>
						<hr class="jagged-rule-dark" />
                        <blockquote class="flow-text comic-sans-text blue-text">On aimerait trop se faire un matching tattoo d'une plume avec un symbole infi...</blockquote> 
                        <p class="comic-sans-text smaller oblique"> Cynthia et Anthony, en couple depuis 3 semaines </p><br/>
						<p class="tahoma-text charcoal-text">
                        Non.
						</p><br/>
						<hr class="jagged-rule-dark" />
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/static_pages/healing.html.erb
	<div class="blog-post-cover" style="margin-top: 4em; padding-top: 3.5em;">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-8">
					<div class="box-shadow-triple water-blueberry-gradient comfortable draggable">
						<h2 class="courier-new-text fittext-h3 heavy white-text bubble-gum-text-shadow">Entretien de mon tatouage</h2>
						<h3 class="red-text arial-text flow-text yellow-text-shadow">Retrouvez ici toutes les astuces du Cowboi pour assurer à votre tatouage une cicatrisation pérenne.</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div style="display: block; clear: both;"></div>
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-9 col-lg-9">
					<div class="double-col pad50">
						<p class="tahoma-text charcoal-text">
							Lorem ipsum no facer prompta vim, movet ubique qui ei. Per no regione aliquid, ea mei nulla scribentur liberavisse. Qui feugait apeirian ut, ne virtute numquam mandamus mea. Eos et enim dicant deterruisset. At nec ceteros mentitum, ex solum putent offendit per.
						</p>
						<hr class="jagged-rule-dark" />
						<p class="tahoma-text charcoal-text">
							Lorem ipsum no facer prompta vim, movet ubique qui ei. Per no regione aliquid, ea mei nulla scribentur liberavisse. No verterem reprimique vix, phaedrum hendrerit an quo. Qui feugait apeirian ut, ne virtute numquam mandamus mea. Eos et enim dicant deterruisset. At nec ceteros mentitum, ex solum putent offendit per.
						</p>
						<hr class="jagged-rule-dark" />
						<p class="tahoma-text charcoal-text">
							Per no regione aliquid, ea mei nulla scribentur liberavisse. No verterem reprimique vix, phaedrum hendrerit an quo. Qui feugait apeirian ut, ne virtute numquam mandamus mea. Eos et enim dicant deterruisset. At nec ceteros mentitum, ex solum putent offendit per.
						</p>
						<hr class="jagged-rule-dark" />
						<blockquote class="flow-text tahoma-text blue-text">What's nice about concrete is that it looks unfinished</blockquote>
						<hr class="jagged-rule-dark" />
						<p class="tahoma-text charcoal-text">
							Lorem ipsum no facer prompta vim, movet ubique qui ei. Per no regione aliquid, ea mei nulla scribentur liberavisse. Vim cu tale ludus possit, discere suavitate nam ad. Qui feugait apeirian ut, ne virtute numquam mandamus mea. Eos et enim dicant deterruisset. At nec ceteros mentitum, ex solum putent offendit per.
						</p>
						<hr class="jagged-rule-dark" />
						<p class="tahoma-text charcoal-text">
							Lorem ipsum no facer prompta vim, movet ubique qui ei. Per no regione aliquid, ea mei nulla scribentur liberavisse. Vim cu tale ludus possit, discere suavitate nam ad. No verterem reprimique vix, phaedrum hendrerit an quo. Qui feugait apeirian ut, ne virtute numquam mandamus mea. Eos et enim dicant deterruisset. At nec ceteros mentitum, ex solum putent offendit per.
						</p>
					</div>
				</div>
		</div>
	</div>
	<div class="row feature-cover">
		<div class="col-sm-12">
			<div class="container">
				<div class="row"><div class="col-sm-12">
					<p class="flow-text times-text cheddar-text wave-text">Venez pas pleurer si vous suivez pas ces consignes</p>
				</div></div>
			</div>
		</div>
	</div>

app/views/static_pages/home.html.erb
<div class="anim-bg-shine draggable">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="fittext-h1 lucida-text yellow-text throb">Cowboi.jpeg</h1>
				<p class="arial-text flow-text vanilla-bean-text">Retrouvez ici tous mes plus grands succès en cassette audio et VHS !</p>
			</div>
		</div>
	</div>
</div>
	<div class="blue-candy">
		<div class="container">
			<div class="row"><h4 class="arial-text white-text"><strong>Mes dernières planches de flashs</strong></h4>
						<div class="scroller-wrap" style="height: 400px;" >
						<div class="scroll-right">
									<div class="scroll-item">
										<img src="../assets/images/brutal-building.jpg" class="xlarge-thumb">
									</div>
									<div class="scroll-item">
										<img src="../assets/images/capsule-tower.jpg" class="xlarge-thumb">
									</div>
									<div class="scroll-item">
										<img src="../assets/images/spomenik.jpg" class="xlarge-thumb">
									</div>
									<div class="scroll-item">
										<img src="../assets/images/rupp-drive-brutalist.jpg" class="xlarge-thumb">
									</div>
									<div class="scroll-item">
										<img src="../assets/images/county-bldg-brutalist.jpg" class="xlarge-thumb">
									</div>
								</div></div>
				</div>
		</div>
	</div>

	

app/views/static_pages/landing.html.erb
<div class="bricks bh100 b100 center">
<div class="reveal hover">
<a class="throb small-btn spin"><strong class="comic-sans-text bubble-gum-text-shadow">Cowboi</strong></a>
<%= link_to image_tag("cowboi_landing.png", class:"secret spin-reverse-fast"), static_pages_home_path %>
</div>
</div>